spring:
  application:
    name: spring-ai-demo

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-secret-key}
      chat:
        options:
          model: gpt-4o-2024-08-06
          temperature: 0.7
          max-tokens: 500

    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-sonnet-20240229
          temperature: 0.7
          max-tokens: 1000